### ISSUE TITLE
Parse failed on "a few seconds ago"

### ISSUE THREAD

**Issue by almartin82** [kvh/parsedatetime#3]
First off -- want to say THANK YOU.  This module saved me a **ton** of time on a project I was working on.

Ran into one input that wasn't handled.  Spotted in the wild while doing a web scrape from https://diy.org/e111e/0005hb

If given the input "a few seconds ago" the parse will fail (closed the exact message, sorry).

I poked around a bit -- if 'a few' was added to self.Modifiers in
https://github.com/kvh/parsedatetime/blob/master/parsedatetime/pdt_locales.py
with a value of 2, might that solve it?

**Comment by kvh** [comment]
Hi,

Sorry for the very belated response, but this is not the official parsedatetime repo. You should leave a note there: http://github.com/bear/parsedatetime/

**Comment by almartin82** [comment]
Closed ten years later as "this was my first ever github issue, and I was not entirely sure what I was doing 😆".
